# Generated by Django 4.2.3 on 2023-07-18 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomBorrow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CustomItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_name",
                    models.CharField(
                        choices=[
                            ("projector", "Projector"),
                            ("keyboard", "Keyboard"),
                            ("mouse", "Mouse"),
                            ("monitor", "Monitor"),
                            ("system-unit", "System-unit"),
                            ("printer", "Printer"),
                            ("toolkit", "Toolkit"),
                            ("extension cable", "Extension cable"),
                        ],
                        max_length=50,
                    ),
                ),
                ("serial_number", models.CharField(max_length=50)),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("working", "Working"),
                            ("faulty", "Faulty"),
                            ("damaged", "Damaged"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "lab",
                    models.CharField(
                        choices=[
                            ("lbb-011", "LBB-011"),
                            ("lbb-015", "LBB-015"),
                            ("lbb-016", "LBB-016"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=150, unique=True)),
                ("password", models.CharField(max_length=128)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("student", "Student"),
                            ("technician", "Technician"),
                            ("admin", "admin"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
