# Generated by Django 4.2.3 on 2023-07-11 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_alter_customuser_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_name",
                    models.CharField(
                        choices=[
                            ("projector", "projector"),
                            ("keyboard", "keyboard"),
                            ("mouse", "mouse"),
                            ("monitor", "monitor"),
                            ("system unit", "system unit"),
                            ("printer", "printer"),
                            ("networking toolkits", "networking toolkit"),
                            ("extension cable", "extension cable"),
                        ],
                        max_length=50,
                    ),
                ),
                ("serial_number", models.CharField(max_length=50)),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("Working", "Working"),
                            ("Faulty", "Faulty"),
                            ("Damaged", "Damaged"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "lab",
                    models.CharField(
                        choices=[
                            ("LBB-011", "LBB-011"),
                            ("LBB-015", "LBB-015"),
                            ("LBB-016", "LBB-016"),
                        ],
                        max_length=50,
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
