# Generated by Django 4.2.3 on 2023-07-16 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_customitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customitem",
            name="date_added",
        ),
        migrations.AlterField(
            model_name="customitem",
            name="condition",
            field=models.CharField(
                choices=[
                    ("working", "Working"),
                    ("faulty", "Faulty"),
                    ("damaged", "Damaged"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="customitem",
            name="item_name",
            field=models.CharField(
                choices=[
                    ("projector", "projector"),
                    ("keyboard", "keyboard"),
                    ("mouse", "mouse"),
                    ("monitor", "monitor"),
                    ("system-unit", "system-unit"),
                    ("printer", "printer"),
                    ("toolkit", "toolkit"),
                    ("extension cable", "extension cable"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="customitem",
            name="lab",
            field=models.CharField(
                choices=[
                    ("lbb-011", "LBB-011"),
                    ("lbb-015", "LBB-015"),
                    ("lbb-016", "LBB-016"),
                ],
                max_length=50,
            ),
        ),
    ]
