# Generated by Django 4.2.3 on 2023-07-16 16:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_remove_customitem_date_added_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customitem",
            name="date_added",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
