# Generated by Django 4.2.3 on 2023-07-16 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_customitem_date_added"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customitem",
            name="date_added",
        ),
    ]
