# Generated by Django 4.2.3 on 2023-07-17 05:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0006_remove_customitem_date_added"),
    ]

    operations = [
        migrations.AddField(
            model_name="customitem",
            name="added_by",
            field=models.ForeignKey(
                default=django.utils.timezone.now,
                on_delete=django.db.models.deletion.CASCADE,
                to="authentication.customuser",
            ),
            preserve_default=False,
        ),
    ]
