# Generated by Django 4.2.3 on 2023-07-17 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0007_customitem_added_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customitem",
            name="added_by",
        ),
    ]
